### ISSUE TITLE
Having trouble with the listening port

### ISSUE THREAD

**Issue by Pwdrkeg** [tothi/log4shell-vulnerable-app#1]
Hello,

When I run the program on Windows, I get this far:

Exception in thread "Thread-128" org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk-17.0.1\bin\java.exe'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:414)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:52)
        at org.gradle.process.internal.DefaultExecActionFactory.javaexec(DefaultExecActionFactory.java:198)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1156)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1151)
        at org.gradle.api.Project$javaexec$6.call(Unknown Source)
<===========--> 87% EXECUTING [46s]ltLauncher.javaExec(DefaultLauncher.groovy:100)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
<===========--> 87% EXECUTING [45s]eflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
<===========--> 87% EXECUTING [44s]ect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
<===========--> 87% EXECUTING [43s]oMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:362)
<===========--> 87% EXECUTING [41s]ime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
<===========--> 87% EXECUTING [39s]herBase$_launchThread_closure3.doCall(LauncherBase.groovy:197)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure3.doCall(LauncherBase.groovy)
<===========--> 87% EXECUTING [16s]eflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
<===========--> 87% EXECUTING [53s]eflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
<===========--> 87% EXECUTING [14s]ection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
<===========--> 87% EXECUTING [13s]ime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
<===========--> 87% EXECUTING [12s](Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
<===========--> 87% EXECUTING [11s]Closure.java:493)
        at java.base/java.lang.Thread.run(Thread.java:833)
<===========--> 87% EXECUTING [10s]
> :appRun

But I don't see the port listening and I can't connect to it manually. 

What am I missing?

**Comment by tothi** [comment]
I don't what is your actual issue, but seems like you are using JDK 17. Use 8 or 11. According to the README:

"JDK is needed. Versions 8 and 11 were tested and are working, 17 seems to have issues."
